apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
clientConnection:
  kubeconfig: "/path/to/kubeconfig/file"
profiles:
- schedulerName: "my-custom-scheduler"
  plugins:
    filter:
      enabled:
      - name: "NodeResourcesFit"
      - name: "NodePorts"
    score:
      enabled:
      - name: "NodeResourcesBalancedAllocation"
      weight: 1
