apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result-ui
  name: result-ui
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-ui
  template:
    metadata:
      labels:
        app: result-ui
    spec:
      containers:
        - image: voting/result-ui:v1.0.15
          name: result-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
          - name: run
            mountPath: /var/run
          - name: cache
            mountPath: /var/cache/nginx
      volumes:
      - name: run
        emptyDir: {}
      - name: cache
        emptyDir: {}
